CREATE DATABASE college;
USE college;

CREATE TABLE student(
 rollno INT PRIMARY KEY,
 name VARCHAR(50),
 marks INT NOT NULL,
 grade VARCHAR(1),
 city VARCHAR(20)
);

CREATE TABLE dept(
 id INT PRIMARY KEY,
 name VARCHAR(25)
 );

INSERT INTO dept VALUES
(101, "ENGLISH"),
(102, "MATHEMATICS"),
(103, "IT"),
(104, "DBMS");

SELECT * FROM dept;
UPDATE dept SET id = 105 WHERE id = 104;

CREATE TABLE teacher(
 id INT PRIMARY KEY,
 name VARCHAR(25),
 dept_id INT,
 FOREIGN KEY (dept_id) REFERENCES dept(id)
 ON DELETE CASCADE
 ON UPDATE CASCADE
);

INSERT INTO teacher VALUES
(01, "RAVI", 101),
(02, "RAM", 102),
(03, "ADAM", 103),
(04, "EVE", 104);

SELECT * FROM teacher;

INSERT INTO student VALUES
(101, "ANIL", 78, "C", "PUNE"),
(102, "BHUMIKA", 93, "A", "MUMBAI"),
(103, "CHETAN", 85, "B", "MUMBAI"),
(104, "DHRUV", 96, "A", "DELHI"),
(105, "EMANUEL", 12, "F", "DELHI"),
(106, "FARAH", 82, "B", "DELHI");
 
 ALTER TABLE student
 ADD COLUMN  age INT NOT NULL DEFAULT 18; 

ALTER TABLE student
MODIFY age VARCHAR(2) NOT NULL DEFAULT "18"; 

ALTER TABLE student
CHANGE age stu_age INT NOT NULL DEFAULT 18; 

ALTER TABLE student
DROP  stu_age; 

ALTER TABLE stu
RENAME TO  student; 

SELECT * FROM student;

INSERT INTO student
(rollno, name, marks, grade, city)
VALUES
(107, "RAGHU", 95, "A", "PUNE");

SELECT * FROM STUDENT WHERE CITY = "DELHI";
SELECT * FROM STUDENT WHERE MARKS > 70;
SELECT * FROM STUDENT WHERE MARKS > 80 AND CITY = "DELHI";
SELECT * FROM STUDENT WHERE MARKS > 80 OR CITY = "DELHI";

SELECT * FROM STUDENT WHERE MARKS BETWEEN 80 AND 90;
SELECT * FROM STUDENT WHERE CITY IN ("DELHI", "MUMBAI");
SELECT * FROM STUDENT WHERE CITY NOT IN ("DELHI", "MUMBAI");

SELECT * FROM STUDENT WHERE MARKS BETWEEN 0 AND 100 LIMIT 3;

SELECT * FROM STUDENT ORDER BY MARKS ASC;
SELECT * FROM STUDENT ORDER BY MARKS DESC;
SELECT * FROM STUDENT ORDER BY MARKS DESC LIMIT 3;

SELECT SUM(MARKS) FROM STUDENT;
SELECT MAX(MARKS) FROM STUDENT;
SELECT MIN(MARKS) FROM STUDENT;
SELECT AVG(MARKS) FROM STUDENT;
SELECT COUNT(MARKS) FROM STUDENT;

SELECT CITY, COUNT(NAME) FROM STUDENT GROUP BY CITY;
SELECT CITY, COUNT(NAME) FROM STUDENT GROUP BY CITY ORDER BY CITY ASC;
SELECT CITY, COUNT(NAME) FROM STUDENT GROUP BY CITY ORDER BY COUNT(NAME) ASC;

SELECT  MAX(MARKS) FROM STUDENT WHERE MARKS <(SELECT MAX(MARKS) FROM STUDENT);

SELECT full_name, MARKS as secondhighestmark
FROM STUDENT
WHERE MARKS = (
SELECT MAX(MARKS)
FROM STUDENT 
WHERE MARKS <(SELECT MAX(MARKS) FROM STUDENT)); 

SELECT * 
FROM STUDENT
WHERE ROLLNO % 2 = 0;

SELECT MAX(MARKS)
FROM (SELECT* FROM STUDENT WHERE CITY = "DELHI") AS TEMP;

SELECT FULL_NAME, MARKS
FROM STUDENT
WHERE CITY = "DELHI"
AND MARKS = (SELECT MAX(MARKS) FROM STUDENT WHERE CITY = "DELHI");

SELECT FULL_NAME, MARKS
FROM STUDENT
WHERE CITY = "DELHI"
ORDER BY MARKS DESC LIMIT 1;

 
SELECT CITY, COUNT(NAME) FROM STUDENT GROUP BY CITY HAVING MAX(MARKS)>80;

SET SQL_SAFE_UPDATES = 0;
UPDATE STUDENT SET GRADE = "O" WHERE GRADE = "A";

TRUNCATE TABLE student;

ALTER TABLE student
CHANGE name full_name VARCHAR(50);

DELETE FROM student
WHERE marks < 80;

ALTER TABLE student
DROP COLUMN grade;

CREATE TABLE student1(
id INT PRIMARY KEY,
name VARCHAR(50)
);

INSERT INTO student1 
VALUES
(101, "ADAM"),
(102, "BOB"),
(103, "CASEY");

CREATE TABLE course(
id INT PRIMARY KEY,
course VARCHAR(50)
);

INSERT INTO course 
VALUES
(102, "ENGLISH"),
(105, "MATH"),
(103, "SCIENCE"),
(107, "COMPUTER SCIENCE");

SELECT * FROM student1;
SELECT * FROM course;

SELECT *
FROM student1 as s
INNER JOIN course as c
ON s.id = c.id;

SELECT *
FROM student1 as s
LEFT JOIN course as c
ON s.id = c.id;

SELECT *
FROM student1 as s
RIGHT JOIN course as c
ON s.id = c.id;

SELECT * FROM student1 as s
LEFT JOIN course as c
on s.id = c.id
UNION
SELECT * FROM student1 as s
RIGHT JOIN course as c
ON s.id = c.id;

SELECT *
FROM student1 as s
LEFT JOIN course as c
ON s.id = c.id
WHERE c.id IS NULL;

SELECT *
FROM student1 as s
RIGHT JOIN course as c
ON s.id = c.id
WHERE s.id IS NULL;

CREATE TABLE employee(
 id INT PRIMARY KEY,
 name VARCHAR(50),
 manager_id INT
);

INSERT INTO employee
VALUES
(101, "ADAM", 102),
(102, "BOB", 104),
(103, "CASEY", 101),
(104, "DONALD", 103);

SELECT * FROM employee;

SELECT a.id as id, a.name as employee, b.name as manager
FROM employee as a
JOIN employee as b
ON a.manager_id = b.id;